apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: todo-app:latest  # Local image built inside Minikube
          imagePullPolicy: Never   # <--- Prevent image pull, use local image
          ports:
            - containerPort: 8087
