apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todo-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80            # Cluster IP port
      targetPort: 8087    # Container port
      nodePort: 30085     # External port on your machine via Minikube
